### ISSUE TITLE
COPYING file is missing from tarball

### ISSUE THREAD

**Issue by opohorel** [breezy-team/fastbencode#1]
I'm trying to package fastbencode to Fedora, because it is a dependency of Breezy.
During the [package review](https://bugzilla.redhat.com/show_bug.cgi?id=2083243#c9), there has been an issue pointed out by mhroncok.

The COPYING file is completely missing from the tarball. Could you please add it and tag the new version?

**Comment by jelmer** [comment]
I'll get this done in the next couple of days.

**Comment by jelmer** [comment]
> BTW recent-enough setuptools allows adding this as a value of license_files argument to setup().
Ah, interesting - I've done it the old-fashioned way for now but will consider that in the future.

**Comment by jelmer** [comment]
> I'll get this done in the next couple of days. Thanks for packaging fastbencode for Fedora :)

s/next couple of days/just now/

**Comment by opohorel** [comment]
@jelmer could you please also tag a new release? There is a commit stating 0.0.8 release, but the latest tag is still v0.0.7

**Comment by jelmer** [comment]
Done - looks like a bug in https://github.com/jelmer/releaser.
