### ISSUE TITLE
Missing releases on pypi

### ISSUE THREAD

**Issue by s-t-e-v-e-n-k** [breezy-team/fastbencode#2]
0.0.8 and 0.0.9 have been tagged and released on GitHub, but have not been uploaded to pypi. Thanks!

**Comment by jelmer** [comment]
Hey Steve!

On Thu, Jun 16, 2022 at 09:44:17PM -0700, Steve Kowalik wrote:
> 0.0.8 and 0.0.9 have been tagged and released on GitHub, but have not been uploaded to pypi. Thanks!
Whoops, I'll try and fix this up later this week.

**Comment by jelmer** [comment]
Done, sorry for the delay.
