### ISSUE TITLE
empty bytes/str should not be allowed to encode/decode

### ISSUE THREAD

**Issue by trim21** [breezy-team/fastbencode#30]
bencode spec doesn't allow encoding or decoding empty (zero length) bytes

**Comment by jelmer** [comment]
Which spec are you referring to ? E.g. https://en.wikipedia.org/wiki/Bencode suggests they are allowed, as does https://wiki.theory.org/BitTorrentSpecification#Byte_Strings

**Comment by trim21** [comment]
Oh, sorry. I misunderstand it...
